{
 "title": "USB",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "maquina", "label": "Server", "query": "up" }
  ]
 },
 "panels": [
  {
   "title": "Estado atual",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "usb_activity{instance=~\"$maquina\"} - usb_activity{instance=~\"$maquina\"} offset 1m",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Dispositivos USB Conectados",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "usb_activity{instance=~\"$maquina\"} > usb_activity{instance=~\"$maquina\"} offset 1m ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Dispositivos USB Desconectados",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "usb_activity{instance=~\"$maquina\"} == usb_activity{instance=~\"$maquina\"} offset 1m ",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}